[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = 
    --cov=praktikum
    --cov-report=html
    --cov-report=term-missing
    --alluredir=allure-results

